project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Bibliothèque de recherche *Mathématiques appliquées* (IPRA)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ujubib/BRmaths_slides
      - icon: mastodon
        href: https://mamot.fr/@UjuBib
format:
  html:
    theme: 
      light: united
      dark: solar
    brand: _brand.yml
    css: styles.css
    lang: fr



